server:
  port: 8080

spring:
  application:
    name: bank-subscription-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: dev_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Use String for the Key
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Use Confluent Avro Serializer for the Value
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        # Essential for Avro: Where is the Schema Registry?
        schema.registry.url: http://localhost:8089
#        spring.json:
#          add.type.headers: true
#        spring.json.type.mapping: "subscriptionEvent:com.bank.payments.subscription.event.SubscriptionEvent"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      # This is the modern OTLP HTTP port for Jaeger
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
  opentelemetry:
    resource-attributes:
      service.name: bank-subscription-service


logging:
  pattern:
    # Adding a clear separator and making traceId stand out
    level: "%5p [%X{traceId:-},%X{spanId:-}] %m%n"
  level:
    root: INFO
    # Your code: Keep this at DEBUG to see your logic
    com.bank.payments.subscription: DEBUG
    # Hibernate: Keep SQL visible but clean
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    # The Noise: Mute these unless you are debugging the connection itself
    io.micrometer.tracing: INFO
    io.opentelemetry: WARN
    org.apache.kafka: WARN
    io.confluent: WARN
    # Spring Web: Helpful for seeing incoming requests without the clutter
    org.springframework.web: INFO
